### ISSUE TITLE
Mensajes de error en consola por paquete Animate_Do

### ISSUE THREAD

**Issue by lrodas** [Klerith/animate_do_package#36]
``Instale el paquete Animate_Do como muestras en la clase para dar el efecto de carga lenta de las imágenes, pero al tener desplegada la consola de logs, sale siempre el mismo error cada vez que cambia una imagen.

Funciona bien y las imágenes se muestran y aparece el efecto, solo es el log del error que aparece cada vez que cambia de imagen.

Este es el código que estoy escribiendo para utilizar la libreria:

```@override
  Widget build(BuildContext context) {
 
    return FadeInUp(
      child: GestureDetector(
        onTap: () => context.push('/home/0/movie/${ movie.id }'),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20),
          child:movie.posterPath.startsWith('assets')
          ? Image.asset(movie.posterPath)
          : Image.network(
              movie.posterPath,
              loadingBuilder: (context, child, loadingProgress) {
                return child;
              },
            )
        )
      ),
    );
  }`


y este es el error obtenido de la libreria
`flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 453 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2 AnimationController.forward (package:flutter/src/animation/animation_controller.dart:453:7)
#3 AnimateDoState.configAnimation.<anonymous closure> (package:animate_do/src/types/animate_do_mixins.dart:37:22)
#4 new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
#5 Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#6 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#7 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#8 <…> `

 Dependencies:
    animate_do: ^3.3.0

**Comment by Klerith** [comment]
Saludos @lrodas 

Ese problema ya lo resolví en una de las versiones siguientes a esa que estás usando, ya voy por la versión 3.3.4.

Puedes probar y confirmar si se resolvió en la última versión?
